name: image_classification_app
description: "Simple image classification app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  image_cropper: ^11.0.0
  photo_view: ^0.15.0
  gal: ^2.3.2
  permission_handler: ^12.0.1
  tflite_flutter: ^0.12.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  android: true
  adaptive_icon_background: "assets/icons/icon.png"  
  adaptive_icon_foreground: "assets/icons/icon_foreground.png" 
  ios: true
  remove_alpha_ios: true

flutter:

  assets:
    - assets/icons/
    - assets/models/
    
  uses-material-design: true